### ISSUE TITLE
Unreact for afk checks

### ISSUE THREAD

**Issue by ewang2002** [ToogaInc/ToogaBooga#115]

**Comment by dmansdman** [comment]
Saw it was in 1.2.0.

**Comment by ewang2002** [comment]
If you want to do unreact, be my guest. Tbh I'm not too sure what the best way to implement it is. @dmansdman

**Comment by dmansdman** [comment]
I think a red button as the last reaction would work.  Someone who presses it AND has reacted will be able to choose a reaction to remove.

**Comment by ewang2002** [comment]
What stops me from reacting to something to get priority/early location, and then unreacting right after?

**Comment by ewang2002** [comment]
Right, so how do you plan on recording this information? Realistically, people aren't going to look at the logs channel.

**Comment by ewang2002** [comment]
This does not appear to be important, thus I am closing it. We can revisit this later if need be.
