### ISSUE TITLE
Reaction points don't work

### ISSUE THREAD

**Issue by nyapat** [ToogaInc/ToogaBooga#181]
title, but to be clear;
When using /stats in the main server, you can have a rune logged but no points, so I looked into it and it relies on an unset property `guildDoc.properties.reactionPoints` (defaulting to []), which is never configurable anywhere as far as I can tell

edit: since they haven't worked in the past (as far as I can see) we could also just retroactively give everyone their points, because all of the info is there, just some math of getting their logged pops, the servers (when fixed) configured reactionPoints for said pop, then giving it

**Comment by ewang2002** [comment]
Ah yes, the idea behind this was that if you popped a rune or key, you could be eligible for points, which can be redeemed for early location/priority. 

Of course, I never got to this as it didn't seem that important at the time. 

For now, don't give people their points until we add this (if at all).

**Comment by ewang2002** [comment]
Closing this for now, as this doesn't seem like something that we'll deal with in the foreseeable future.
