### ISSUE TITLE
Require loc to start afk check

### ISSUE THREAD

**Issue by dmansdman** [ToogaInc/ToogaBooga#220]
This was a feature of Ooga, and will prevent leaders from opening VC without inputting loc.  This is especially relevant considering elite loc implementation, where leaders who forget to put in loc will result in elite raiders not getting loc.

**Comment by ewang2002** [comment]
How should this be implemented for headcounts? Recall that raid leaders can start a raid directly from a finished headcount.

**Comment by dmansdman** [comment]
I can't think of a reason why we would progress from a pre afk check to an afk check without a location.  

To clarify, this is only for when an afk has been started and is transitioning from pre to actual afk

**Comment by dmansdman** [comment]
Headcount irrelevant.
