### ISSUE TITLE
Parsing VCless runs by comparing who is in the server and who isn't

### ISSUE THREAD

**Issue by Deaththth** [ToogaInc/ToogaBooga#266]
Simple parse command to check which IGNs in the /who are registered to this or another server Guill is in. 
Can be called serverparse.

**Comment by Deaththth** [comment]
Note, this would count under parses when it comes to quota for securities.

**Comment by Deaththth** [comment]
Alternatively, the info logged by who reacted in a vcless raid with the JOIN button (see https://github.com/ToogaInc/ToogaBooga/issues/243) can be used to crosscheck with the /who instead.

**Comment by dmansdman** [comment]
Parses vcless runs by checking who has officially joined the run using the join button or confirmed early react.
