### ISSUE TITLE
Auto-verification not working

### ISSUE THREAD

**Issue by sjkd23** [ToogaInc/ToogaBooga#288]
It gets stuck at: “@user is now waiting for the bot to verify their IGN, (ign).”

**Comment by sjkd23** [comment]
![Uploading 29CE87B6-6EF4-460D-9545-29C8321CE8D9.jpeg…]()

**Comment by ewang2002** [comment]
Looking into this.

**Comment by ewang2002** [comment]
Issue fixed. Waiting for @sjkd23 to respond with resolution.
