### ISSUE TITLE
Allow to configure one or more images to display after every afk

### ISSUE THREAD

**Issue by Deaththth** [ToogaInc/ToogaBooga#33]
Mainly important for shatters but can be used for requirements as well which is why multiple images should be allowed.
Shatters image in question: https://media.discordapp.net/attachments/893216268914679889/898057319944957963/patience.gif

**Comment by ewang2002** [comment]
It's probably not possible to support multiple images because images on embeds take time to fully load. So, if the bot updates the AFK check embed every 5 seconds or so, users may not see the images at all.

**Comment by Deaththth** [comment]
Not needed anymore in my opinion
